### ISSUE TITLE
Failed CRC in Home Assistant

### ISSUE THREAD

**Issue by hillstub** [crownstone/crownstone-lib-python-uart#6]
Hi guys,
I updated all the crownstones to the new firmware.

when I'm using the Home Assistant integration it does not work with the uart dongle. In the log of Home Assistant it says:

```
2021-01-19 09:19:31 WARNING (Thread-37) [crownstone_uart.core.uart.UartReadBuffer] Failed CRC
```

**Comment by AlexDM0** [comment]
Hi, there has been a breaking change in the new firmware and the new HA version which supports this, should have been released yesterday. I'll check up on it to see if everything is going OK there.

Sorry for the inconvenience. We'll release it ASAP.

**Comment by AlexDM0** [comment]
Hi, the new version is now released. Take a look here:
https://github.com/crownstone/crownstone-home-assistant/releases/tag/v1.5.4

Cheers
